# Generated by Django 2.0.2 on 2018-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hospital', '0003_auto_20180305_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostpital',
            name='api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.Service'),
        ),
    ]
