# Generated by Django 2.0.2 on 2018-03-05 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hospital', '0004_auto_20180305_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
