# Generated by Django 2.0.2 on 2018-03-07 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0005_event_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostpital',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='additionalservice',
            old_name='hospital',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='hospital',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='hospital',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='hospital',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='hospital',
            new_name='Hospital',
        ),
    ]
