# Generated by Django 2.0.2 on 2018-03-07 11:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hospital', '0006_auto_20180307_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalservice',
            old_name='Hospital',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Hospital',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Hospital',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='Hospital',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Hospital',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Hospital',
            new_name='hospital',
        ),
    ]
