# Generated by Django 2.0.2 on 2018-03-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20180307_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent_ac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent_nonac',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
